### ISSUE TITLE
Add empty UI handling

### ISSUE THREAD

**Issue by tvtusc25** [ryanmogauro/Scheduling-Project#92]
When selections, notifications, etc. are empty add a "Nothing to see here..." message in place of expected content

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Implemented a feature to display 'Nothing to see here...' message when selections, notifications, or other relevant sections are empty. This change improves user experience by providing feedback when there's no content to display.

You can review changes in this commit: https://github.com/mnmnk43434/ryanmogauro-Scheduling-Project-92/commit/2bcc1595a64952c04429def228cc1cebbc9cb355.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
